version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: application
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./assets/data:/docker-entrypoint-initdb.d

  apache:
    image: 'php:7.2-apache'
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    links:
      - db 